### ISSUE TITLE
compatibility with older macos

### ISSUE THREAD

**Issue by kintaro1981** [federicocappelli/TorrentHound#3]
How about compatibility with High Sierra or Mojave?

**Comment by federicocappelli** [comment]
Hi @kintaro1981 , Torrent Hound was written in Swift and SwiftUI that were not available in High Sierra and Mojave or were in a very early stage of development and were missing a lot of features at the time. 
Making Torrent Hound back-compatible with a OS released more than 5 years ago is not sustainable for me and would require a lot of work.
